Feeddit/Models/Article.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Feeddit.Models
{
    public class Article
    {
        [Key]
        public long ID { get; set; }

       
        public int UserID { get; set; }

       
        public DateTime DateCreated { get; set; }

        [Required(ErrorMessage = "Molimo unesite naziv članka.")]
        [Display(Name = "Headline")]
        public string Title { get; set; }
        [Required]
        //[RegularExpression("^[(http(s)?):\\/\\/(www\\.)?a-zA-Z0-9@:%._\\+~#=]{2,256}\\.[a-z]{2,6}\\b([-a-zA-Z0-9@:%_\\+.~#?&//=]*)$", ErrorMessage = "Uneseni link nije ispravan.")]
        [Url()]
        [Display(Name = "Link")]
        public string ArticleUrl { get; set; }
        [Required(ErrorMessage = "Molimo unesite ime autora.")]
        public string Author { get; set; }

        [Display(Name = "Vote #")]
        public int Votes { get; set; }

        public User User { get; set; }

       
    }


}

Feeddit/Controllers/ArticlesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Feeddit.Models;
using Microsoft.AspNet.Identity;
using Feeddit.DAL;
using PagedList;
using NLog;

namespace Feeddit.Controllers
{
    [CustomAuthorize]
    public class ArticlesController : Controller
    {
        private FeedditContext db = new FeedditContext();
        private static Logger logger = LogManager.GetCurrentClassLogger();
        // GET: Articles
        public ActionResult Index(string sortOrder, string currentFilter, string searchString, int? page)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.TitleSortParm = String.IsNullOrEmpty(sortOrder) ? "title_desc" : "";
            ViewBag.AuthorSortParm = String.IsNullOrEmpty(sortOrder) ? "author_desc" : "";
            ViewBag.VotesSortParm = String.IsNullOrEmpty(sortOrder) ? "votes_desc" : "";

            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;
            //if (searchString == null ||  searchString.Trim().Count() < 4)
            //{
            //    ViewBag.ErrorMessage = "Za pretragu morate unijeti bar 3 znaka.";
            //    return View();
            //}

            var articles = from m in db.Articles
                           select m;

            if (!String.IsNullOrEmpty(searchString))
            {
                articles = articles.Where(s => s.Title.Contains(searchString));

            }
            switch (sortOrder)
            {
                case "title_desc":
                    articles = articles.OrderByDescending(s => s.Title);
                    break;
                case "author_desc":
                    articles = articles.OrderByDescending(s => s.Author);
                    break;
                case "votes_desc":
                    articles = articles.OrderByDescending(s => s.Votes);
                    break;
                default:
                    articles = articles.OrderBy(s => s.Title);
                    break;
            }
            int pageSize = 5;
            int pageNumber = (page ?? 1);
            if (this.db.Articles.Count() == 0)
            {
                TempData["alert"] = "Trenutno nema članaka za prikaz.";
                TempData["aType"] = "danger";
            }
            ViewBag.ListArticle = this.db.Articles.ToList();
            return View(articles.ToPagedList(pageNumber, pageSize));

        }


        public ActionResult IndexKorisnik(string sortOrder, string currentFilter, string searchString, int? page)
        {

            ViewBag.CurrentSort = sortOrder;
            ViewBag.TitleSortParm = String.IsNullOrEmpty(sortOrder) ? "title_desc" : "";
            ViewBag.AuthorSortParm = String.IsNullOrEmpty(sortOrder) ? "author_desc" : "";
            ViewBag.VotesSortParm = String.IsNullOrEmpty(sortOrder) ? "votes_desc" : "";

            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;
            //if (searchString == null ||  searchString.Trim().Count() < 4)
            //{
            //    ViewBag.ErrorMessage = "Za pretragu morate unijeti bar 3 znaka.";
            //    return View();
            //}
            var userID = Convert.ToInt32(Session["UserID"]);

            string userRole = Session["Rola"].ToString();

            var articles = from m in db.Articles
                           select m;

            if (!userRole.Contains("Admin"))
            {
                articles = from m in db.Articles.Where(m => m.UserID == userID) select m;

            }

            if (!String.IsNullOrEmpty(searchString))
            {
                articles = articles.Where(s => s.Title.Contains(searchString));

            }
            switch (sortOrder)
            {
                case "title_desc":
                    articles = articles.OrderByDescending(s => s.Title);
                    break;
                case "author_desc":
                    articles = articles.OrderByDescending(s => s.Author);
                    break;
                case "votes_desc":
                    articles = articles.OrderByDescending(s => s.Votes);
                    break;
                default:
                    articles = articles.OrderBy(s => s.Title);
                    break;
            }
            int pageSize = 5;
            int pageNumber = (page ?? 1);
            if (this.db.Articles.Count() == 0)
            {
                TempData["alert"] = "Trenutno nema članaka za prikaz.";
                TempData["aType"] = "danger";
            }
            ViewBag.ListArticle = this.db.Articles.ToList();
            return View(articles.ToPagedList(pageNumber, pageSize));
        }

        [HttpPost]
        public JsonResult IndexAuto(string Prefix)
        {
            //if (searchTerm.Length < 3)
            //{
            //    return null;
            //}
            //Searching records from list using LINQ query  
            var articles = from m in db.Articles
                           select m;

            if (!String.IsNullOrEmpty(Prefix))
            {
                articles = articles.Where(s => s.Title.Contains(Prefix));
            }
            return Json(articles, JsonRequestBehavior.AllowGet);
        }

        // GET: Articles/Details/5
        public ActionResult Details(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Article article = db.Articles.Find(id);
            if (article == null)
            {
                return HttpNotFound();
            }
            return View(article);
        }

        // GET: Articles/Create
        public ActionResult Create()
        {
            using (FeedditContext db = new FeedditContext())
            {
                int id = (int)Session["UserID"];
                var userDetails = db.Users.Where(x => x.ID == id).FirstOrDefault();
                if (userDetails != null)
                {
                    ViewBag.Name = userDetails.Name;
                }
            }


            return View();
        }

        // POST: Articles/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Title,ArticleUrl,Author")] Article article)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    // get id of currently logged user
                    int UserID = Convert.ToInt32(Session["UserID"]);
                    article.UserID = UserID;
                    article.DateCreated = DateTime.Now;
                    db.Articles.Add(article);
                    db.SaveChanges();
                    TempData["alert"] = "Članak uspješno unesen.";
                    TempData["aType"] = "success";
                    logger.Info("Created new article, id = " + article.ID + " , date created: " + DateTime.Now + ", user id = " + article.UserID);
                    return RedirectToAction("Index");
                }
                else
                {
                    TempData["alert"] = "Error occured during article creation. Please try again.";
                    TempData["aType"] = "danger";

                }
            }
            catch (DataException ex)
            {
                logger.Error("Error during article creation: " + ex.Message, ex);
                ModelState.AddModelError("ex", "Unable to save changes. Try again, and if the problem persists contact your system administrator.");
            }
            return View(article);
        }

        // GET: Articles/Edit/5
        public ActionResult Edit(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Article article = db.Articles.Find(id);
            if (article == null)
            {
                return HttpNotFound();
            }
            return View(article);
        }

        // POST: Articles/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,UserID,DateCreated,Title,ArticleUrl,Author,Votes")] Article article)
        {
            // get id of currently logged user
            int UserID = Convert.ToInt32(Session["UserID"]);

            if (ModelState.IsValid)
            {
                db.Entry(article).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(article);
        }

        // GET: Articles/Delete/5
        public ActionResult Delete(string sortOrder, string currentFilter, string searchString, int? page)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.TitleSortParm = String.IsNullOrEmpty(sortOrder) ? "title_desc" : "";
            ViewBag.AuthorSortParm = String.IsNullOrEmpty(sortOrder) ? "author_desc" : "";
            ViewBag.VotesSortParm = String.IsNullOrEmpty(sortOrder) ? "votes_desc" : "";

            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;
            //if (searchString == null ||  searchString.Trim().Count() < 4)

Feeddit/Views/Articles/Create.cshtml
@model Feeddit.Models.Article

@{
    ViewBag.Title = "Add new article";
}
<div class="card shadow">
    <div class="card-header">
        <h2>Add new article</h2>
        @if (TempData["alert"] != null)
        {
            <div class="alert alert-@TempData["aType"] alert-sm text-center container topalert">
                @TempData["alert"]
            </div>
        }

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">

                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                <div class="form-group">
                    @Html.Label("Vote #:")
                    <div class="col-md-2">
                        <input type="text" id="votes" value="0" class="form-control" readonly />

                    </div>
                </div>
                <div class="form-group">
                    @Html.Label("By user:")
                    <div class="col-md-2">
                        <input type="text" id="userby" value="@ViewBag.Name" class="form-control" readonly />
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-2">
                        @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.ArticleUrl, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-2">
                        @Html.EditorFor(model => model.ArticleUrl, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.ArticleUrl, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Author, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-2">
                        @Html.EditorFor(model => model.Author, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Author, "", new { @class = "text-danger" })
                    </div>
                </div>



                <div class="form-group">
                    <div class="row">
                        <div class="col-md-1">
                            <input type="submit" value="Publish" class="btn btn-lang btn-lg" />
                        </div>
                        <div class="col-md-1">
                            <input type="button" value="Cancel" class="btn btn-lang btn-lg"
                                   onclick="javascript:document.location.href='@Url.Action("Index", "Articles")'" />

                        </div>
                    </div>
                </div>

                </div>
                }
            </div>


        </div>


                @section Scripts {
                    @Scripts.Render("~/bundles/jqueryval")
                }

Feeddit/Views/Articles/Delete.cshtml
@*@model IEnumerable<Feeddit.Models.Article>*@
@model PagedList.IPagedList<Feeddit.Models.Article>
@using PagedList.Mvc;
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "Delete Articles";
}



@using (Html.BeginForm("DeleteSelected", "Articles", FormMethod.Post))
{
    <div class="card shadow">
        <div class="card-header">
            @*@Html.ActionLink("Delete selected", "DeleteSelected", null, new { @class = "btn btn-lang btn-sm" })*@
            <div class="col-md-2 col-12 text-center">
                <button type="submit" value="DeleteSelected" class="btn btn-lang btn-sm" onclick="return confirm('Da li ste sigurni?')"><i class="btn btn-lang btn-sm"></i> Delete selected</button>
                <br /><br />  
            </div>
        </div>
    </div>
    @*<button type="submit" value="Delete" class="btn btn-lang btn-sm" onclick="return confirm('Are you sure to delete selected?')"><i class="fa fa-trash-o"></i> Delete</button>
        <br /><br />*@
    <div class="tab-content" id="myTabContent">
        <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">

            <div class="table-responsive card-body">
                <table id="DataTable" class="table  dTable table-md" style="width:100%">
                    <thead>
                        <tr>

                            <th>
                                @*@Html.DisplayNameFor(model => model.Title)*@
                                @Html.ActionLink("Title", "Delete", new { sortOrder = ViewBag.TitleSortParm, currentFilter = ViewBag.CurrentFilter })
                            </th>
                            <th>
                                ArticleUrl
                            </th>
                            <th>
                                @*@Html.DisplayNameFor(model => model.Author)*@
                                @Html.ActionLink("Author", "Delete", new { sortOrder = ViewBag.AuthorSortParm, currentFilter = ViewBag.CurrentFilter })
                            </th>
                            <th>
                                @*@Html.DisplayNameFor(model => model.Votes)*@
                                @Html.ActionLink("Votes", "Delete", new { sortOrder = ViewBag.VotesSortParm, currentFilter = ViewBag.CurrentFilter })
                            </th>

                            <th><input type="checkbox" id="checkBoxAll" class="custom-checkbox" /></th>

                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var article in ViewBag.ListArticle)
                        {
                            <tr>
                                <td>
                                    @article.Title
                                </td>
                                <td>
                                    @article.ArticleUrl
                                </td>
                                <td>
                                    @article.Author
                                </td>
                                <td>
                                    @article.Votes
                                </td>
                                <td><input type="checkbox" name="ID" value="@article.ID" class="custom-checkbox chkCheckBoxId" /></td>

                            </tr>

                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    <br />
}
Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount

@*@Html.PagedListPager(Model, page => Url.Action("Index",
    new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }))*@


@Html.PagedListPager(Model, page => Url.Action("Delete", new { page = page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }), PagedListRenderOptions.MinimalWithPageCountText)
@section Scripts {
    <script type="text/javascript">

        $(document).ready(function () {
            $('#DataTable').DataTable({
                paging: false,
                searching: false
            });
            $('#checkBoxAll').click(function () {
                if ($(this).is(":checked")) {
                    $(".chkCheckBoxId").prop("checked", true)
                }
                else {
                    $(".chkCheckBoxId").prop("checked", false)
                }
            });
        });
    </script>
}

Feeddit/Views/Articles/Details.cshtml
@model Feeddit.Models.Article

@{
    ViewBag.Title = "Details";
}

<div class="card shadow">
    <div class="card-header">

        <div>

            <hr />
            <dl class="dl-horizontal">
                <dt>
                    @Html.DisplayNameFor(model => model.UserID)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.UserID)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.DateCreated)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.DateCreated)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Title)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Title)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.ArticleUrl)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.ArticleUrl)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Author)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Author)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Votes)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Votes)
                </dd>

            </dl>
        </div>

      
        </div>
    </div>

Feeddit/Views/Articles/Edit.cshtml
@model Feeddit.Models.Article

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Article</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.UserID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UserID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UserID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DateCreated, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DateCreated, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DateCreated, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ArticleUrl, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ArticleUrl, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ArticleUrl, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Author, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Author, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Author, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Votes, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Votes, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Votes, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Feeddit/Views/Articles/Index.cshtml
@*@model IEnumerable<Feeddit.Models.Article>*@
@model PagedList.IPagedList<Feeddit.Models.Article>
@using PagedList.Mvc;
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "Articles";
}
@*section Scripts {

    <script type="text/javascript">

        $(function () {
            $("#txtSearch").autocomplete({
                source: '@Url.Action("IndexAuto", "Articles")',
                minLength: 3
            });
        });
    </script>

        }*@

<p>

    @using (Html.BeginForm("Index", "Articles", FormMethod.Get))
    {
    <p>
        @*Title: @Html.TextBox("SearchString") <br />*@
        Title:   @Html.TextBox("SearchString", ViewBag.CurrentFilter as string)
        <input type="submit" value="Filter" class="btn btn-lang btn-sm" />
    </p>
    }
    <div class="card shadow">
        <div class="card-header text-center">
            @Html.ActionLink("Add new article", "Create", null, new { @class = "btn btn-lang btn-lg" })
            <div class="col-md-2 col-12 text-right">

            </div>
        </div>
    </div>
    <div class="tab-content" id="myTabContent">
        <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">

            <div class="table-responsive card-body">
                <table class="table  dTable table-md" style="width:100%">
                    <tr>
                        <th>

                            @Html.ActionLink("Votes", "Index", new { sortOrder = ViewBag.VotesSortParm, currentFilter = ViewBag.CurrentFilter })
                        </th>
                        <th>
                            ArticleUrl
                        </th>
                        <th>

                            @Html.ActionLink("Headline", "Index", new { sortOrder = ViewBag.TitleSortParm, currentFilter = ViewBag.CurrentFilter })
                        </th>

                        <th>

                            @Html.ActionLink("Author", "Index", new { sortOrder = ViewBag.AuthorSortParm, currentFilter = ViewBag.CurrentFilter })
                        </th>

                        @*<th></th>*@
                    </tr>

                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>

                                @Html.DisplayFor(modelItem => item.Votes)
                            </td>
                            <td>
                                @Html.ActionLink(@item.ArticleUrl, "Details", "Articles", new { id = long.Parse(item.ID.ToString()) }, null)


                            </td>
                            <td>
                                @Html.ActionLink(@item.Title, "Details", "Articles", new { id = long.Parse(item.ID.ToString()) }, null)

                            </td>
                            <td>

                                @Html.DisplayFor(modelItem => item.Author)
                            </td>

                            @*<td>
                                    @Html.ActionLink("Edit", "Edit", new { id = item.ID }) |
                                    @Html.ActionLink("Details", "Details", new { id = item.ID })
                                    @Html.ActionLink("Delete", "Delete", new { id = item.ID })

                                </td>*@
                        </tr>

                    }

                </table>
            </div>
        </div>
    </div>
    <br />

    Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount

    @*@Html.PagedListPager(Model, page => Url.Action("Index",
        new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }))*@

    @Html.PagedListPager(Model, page => Url.Action("Index", new { page = page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }), PagedListRenderOptions.MinimalWithPageCountText)