Feeddit/Controllers/ArticleVotingController.cs
using Feeddit.DAL;
using Feeddit.Models;
using Feeddit.ViewModel;
using NLog;
using PagedList;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Feeddit.Controllers
{
    [CustomAuthorize]
    public class ArticleVotingController : Controller
    {
        private static Logger logger = LogManager.GetCurrentClassLogger();
        // GET: ArticleVoting
        [AcceptVerbs(HttpVerbs.Get)]
        public ActionResult Index(string sortOrder, string currentFilter, string searchString, int? page)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.TitleSortParm = String.IsNullOrEmpty(sortOrder) ? "title_desc" : "";
            ViewBag.AuthorSortParm = String.IsNullOrEmpty(sortOrder) ? "author_desc" : "";
            ViewBag.VotesSortParm = String.IsNullOrEmpty(sortOrder) ? "votes_desc" : "";

            FeedditContext context = new FeedditContext();

            List<ArticleVoting> ArticleVotingVM = new List<ArticleVoting>();

            //var votingList = (from article in context.Articles

            //                  join vote in context.Votes on article.ID equals vote.ArticleID
            //                  join user in context.Users on vote.UserID equals user.ID
            //                  select new { article.Title, article.Author, article.Votes, article.ArticleUrl, vote.VoteNumber, article.ID, userID = user.ID });
            var votingList = (from article in context.Articles

                              join vote in context.Votes on article.ID equals vote.ArticleID
                              join user in context.Users on article.UserID equals user.ID
                              select new { article.Title, article.Author, article.Votes, article.ArticleUrl, vote.VoteNumber, article.ID, userID = user.ID });

            if (votingList.Count() == 0)
            {
                TempData["alert"] = "Trenutno nema članaka za prikaz.";
                TempData["aType"] = "danger";
            }
            foreach (var item in votingList)

            {

                ArticleVoting objcvm = new ArticleVoting(); // ViewModel

                objcvm.Title = item.Title;

                objcvm.Author = item.Author;

                objcvm.Votes = item.Votes;

                objcvm.ArticleUrl = item.ArticleUrl;

                objcvm.VoteNumber = item.VoteNumber;

                objcvm.ArticleID = item.ID;

                objcvm.UserID = item.userID;

                ArticleVotingVM.Add(objcvm);

            }
            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;
            //if (searchString == null ||  searchString.Trim().Count() < 4)
            //{
            //    ViewBag.ErrorMessage = "Za pretragu morate unijeti bar 3 znaka.";
            //    return View();
            //}



            if (!String.IsNullOrEmpty(searchString))
            {
                //votingList = votingList.Where(s => s.Title.Contains(searchString));
                ArticleVotingVM = ArticleVotingVM.Where(s => s.Title.Contains(searchString)).ToList();
            }
            switch (sortOrder)
            {
                case "title_desc":
                    //votingList = votingList.OrderByDescending(s => s.Title);
                    ArticleVotingVM = ArticleVotingVM.OrderByDescending(s => s.Title).ToList();
                    break;
                case "author_desc":
                    //votingList = votingList.OrderByDescending(s => s.Author);
                    ArticleVotingVM = ArticleVotingVM.OrderByDescending(s => s.Author).ToList();
                    break;
                case "votes_desc":
                    //votingList = votingList.OrderByDescending(s => s.Votes);
                    ArticleVotingVM = ArticleVotingVM.OrderByDescending(s => s.Votes).ToList();
                    break;
                default:
                    //votingList = votingList.OrderBy(s => s.Title);
                    ArticleVotingVM = ArticleVotingVM.OrderBy(s => s.Title).ToList();
                    break;
            }
            int pageSize = 5;
            int pageNumber = (page ?? 1);

            return View(ArticleVotingVM.ToPagedList(pageNumber, pageSize));

        }


        public ActionResult Upvote(long id)
        {

            using (FeedditContext db = new FeedditContext())
            {
                int UserID = Convert.ToInt32(Session["UserID"]);
                Article article = db.Articles.Find(id);
                Vote vote = db.Votes.Where(b => b.ArticleID == article.ID && b.UserID == UserID).FirstOrDefault();
                if (vote != null)
                {
                    int brGlasova = vote.VoteNumber;
                    if (brGlasova == 0)
                    {
                        vote.VoteNumber = 1;
                        article.Votes++;
                        db.SaveChanges();
                        TempData["alert"] = "Vaš glas je uspješno zaprimljen.";
                        TempData["aType"] = "success";
                    }
                    else
                    {
                        TempData["alert"] = "Već ste glasali!";
                        TempData["aType"] = "danger";
                        db.SaveChanges();
                    }
                }
            }

            return RedirectToAction("Index");
        }


        public ActionResult Downvote(long id)
        {

            using (FeedditContext db = new FeedditContext())
            {
                int UserID = Convert.ToInt32(Session["UserID"]);
                Article article = db.Articles.Find(id);
                Vote vote = db.Votes.Where(b => b.ArticleID == article.ID && b.UserID == UserID).FirstOrDefault();
                if (vote != null)
                {
                    int brGlasova = vote.VoteNumber;
                    if (brGlasova == 1)
                    {
                        vote.VoteNumber = 0;
                        article.Votes--;
                        db.SaveChanges();
                        TempData["alert"] = "Vaš glas je uspješno opozvan.";
                        TempData["aType"] = "success";
                    }
                    else
                    {
                        TempData["alert"] = "Već ste glasali!";
                        TempData["aType"] = "danger";
                        db.SaveChanges();
                    }
                }
            }

            return RedirectToAction("Index");
        }


        // GET: Articles/Create
        public ActionResult Create()
        {
            using (FeedditContext db = new FeedditContext())
            {
                int id = (int)Session["UserID"];
                var userDetails = db.Users.Where(x => x.ID == id).FirstOrDefault();
                if (userDetails != null)
                {
                    ViewBag.Name = userDetails.Name;
                }
            }


            return View();
        }

        // POST: Articles/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Title,ArticleUrl,Author")] Article article)
        {
            FeedditContext db = new FeedditContext();
            try
            {
                if (ModelState.IsValid)
                {
                    // get id of currently logged user
                    int UserID = Convert.ToInt32(Session["UserID"]);
                    article.UserID = UserID;
                    article.DateCreated = DateTime.Now;
                    db.Articles.Add(article);

                    db.SaveChanges();
                    // mora se za glas kreirati novi zapis
                    Vote vote = new Vote();
                    vote.ArticleID = article.ID;
                    vote.UserID = UserID;
                    vote.VoteNumber = 0;
                    db.Votes.Add(vote);
                    db.SaveChanges();
                    TempData["alert"] = "Članak uspješno unesen.";
                    TempData["aType"] = "success";
                    logger.Info("Created new article, id = " + article.ID + " , date created: " + DateTime.Now + ", user id = " + article.UserID);
                    return RedirectToAction("Index");
                }
                else
                {
                    TempData["alert"] = "Error occured during article creation. Please try again.";
                    TempData["aType"] = "danger";

                }
            }
            catch (DataException ex)
            {
                logger.Error("Error during article creation: " + ex.Message, ex);
                ModelState.AddModelError("ex", "Unable to save changes. Try again, and if the problem persists contact your system administrator.");
            }
            return View(article);
        }
    }

}

Feeddit/Views/ArticleVoting/Create.cshtml
@model Feeddit.Models.Article

@{
    ViewBag.Title = "Add new article";
}
<div class="card shadow">
    <div class="card-header">
        <h2>Add new article</h2>
        @if (TempData["alert"] != null)
        {
            <div class="alert alert-@TempData["aType"] alert-sm text-center container topalert">
                @TempData["alert"]
            </div>
        }

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">

                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                <div class="form-group">
                    @Html.Label("Vote #:")
                    <div class="col-md-2">
                        <input type="text" id="votes" value="0" class="form-control" readonly />

                    </div>
                </div>
                <div class="form-group">
                    @Html.Label("By user:")
                    <div class="col-md-2">
                        <input type="text" id="userby" value="@ViewBag.Name" class="form-control" readonly />
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-2">
                        @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.ArticleUrl, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-2">
                        @Html.EditorFor(model => model.ArticleUrl, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.ArticleUrl, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Author, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-2">
                        @Html.EditorFor(model => model.Author, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Author, "", new { @class = "text-danger" })
                    </div>
                </div>



                <div class="form-group">
                    <div class="row">
                        <div class="col-md-1">
                            <input type="submit" value="Publish" class="btn btn-lang btn-lg" />
                        </div>
                        <div class="col-md-1">
                            <input type="button" value="Cancel" class="btn btn-lang btn-lg"
                                   onclick="javascript:document.location.href='@Url.Action("Index", "ArticleVoting")'" />

                        </div>
                    </div>
                </div>

                </div>
                }
            </div>


        </div>


                @section Scripts {
                    @Scripts.Render("~/bundles/jqueryval")
                }

Feeddit/Views/ArticleVoting/Index.cshtml
@*@model IEnumerable<Feeddit.Models.Article>*@
@model PagedList.IPagedList<Feeddit.ViewModel.ArticleVoting>
@using PagedList.Mvc;
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "Articles";
}
@*section Scripts {

    <script type="text/javascript">

        $(function () {
            $("#txtSearch").autocomplete({
                source: '@Url.Action("IndexAuto", "Articles")',
                minLength: 3
            });
        });
    </script>

        }*@

<p>
    @if (TempData["alert"] != null)
    {
        <div class="alert alert-@TempData["aType"] alert-sm text-center container topalert">
            @TempData["alert"]
        </div>
    }
    @using (Html.BeginForm("Index", "ArticleVoting", FormMethod.Get))
    {
    <p>
        @*Title: @Html.TextBox("SearchString") <br />*@
        Title:   @Html.TextBox("SearchString", ViewBag.CurrentFilter as string)
        <input type="submit" value="Filter" class="btn btn-lang btn-sm" />
    </p>
    }
    <div class="card shadow">
        <div class="card-header text-center">
            @Html.ActionLink("Add new article", "Create", "Articles", new { @class = "btn btn-lang btn-lg" })
            <div class="col-md-2 col-12 text-right">

            </div>
        </div>
    </div>
    <div class="tab-content" id="myTabContent">
        <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">

            <div class="table-responsive card-body">
                <table class="table  dTable table-md" style="width:100%">
                    <tr>
                        <th>

                            @Html.ActionLink("Votes", "Index", new { sortOrder = ViewBag.VotesSortParm, currentFilter = ViewBag.CurrentFilter })
                        </th>
                        <th>
                            ArticleUrl
                        </th>
                        <th>
                            @Html.ActionLink("Headline", "Index", new { sortOrder = ViewBag.TitleSortParm, currentFilter = ViewBag.CurrentFilter })
                        </th>

                        <th>
                            @Html.ActionLink("Author", "Index", new { sortOrder = ViewBag.AuthorSortParm, currentFilter = ViewBag.CurrentFilter })
                        </th>
                        <th></th>
                        <th></th>

                    </tr>

                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>

                                @Html.DisplayFor(modelItem => item.Votes)
                            </td>
                            <td>
                                @Html.ActionLink(@item.ArticleUrl, "Details", "Articles", new { id = long.Parse(item.ArticleID.ToString()) }, null)


                            </td>
                            <td>
                                @Html.ActionLink(@item.Title, "Details", "Articles", new { id = long.Parse(item.ArticleID.ToString()) }, null)

                            </td>
                            <td>

                                @Html.DisplayFor(modelItem => item.Author)
                            </td>
                            <td>
                                @if (item.VoteNumber == 0)
                                {
                                    <button type="button" class="btn btn-default" value="Glasaj" onclick="location.href='@Url.Action("Upvote", "ArticleVoting", new { id = long.Parse(item.ArticleID.ToString()) })'">
                                        <i class="fa fa-thumbs-up"></i>
                                    </button>
                                }
                            </td>
                            <td>
                                @if (item.VoteNumber == 1)
                                {
                                    <button type="button" class="btn btn-default" value="Glasaj" onclick="location.href='@Url.Action("Downvote", "ArticleVoting", new { id = long.Parse(item.ArticleID.ToString()) })'">
                                        <i class="fa fa-thumbs-down"></i>
                                    </button>
                                }
                            </td>

                        </tr>

                    }

                </table>
            </div>
        </div>
    </div>
    <br />

    Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount

    @Html.PagedListPager(Model, page => Url.Action("Index", new { page = page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }), PagedListRenderOptions.MinimalWithPageCountText)